[package]
edition = "2018"
name = "cathlamet"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
description = "Distributed systems substrate"
documentation = "https://docs.rs/cathlamet/"
repository= "https://github.com/hmwill/cathlamet"
license = "MIT"

[dependencies]
bitflags = "1.0"
bytes = "0.4.11"
clap = "2.32.0"
cranelift = "0.24.0"
error-chain = "0.12.0"
httparse = "1.3.3"
libc = "0.2"
may = "0.3"
log = "0.4"
pretty_env_logger = "0.2"
serde = "1.0.80"
serde_json = "1.0.33"