[package]
edition = "2018"
name = "cathlamet"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
description = "Distributed systems substrate"
documentation = "https://docs.rs/cathlamet/"
repository= "https://github.com/hmwill/cathlamet"
license = "MIT"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
bitflags = "1.1"
bytes = "0.4"
clap = "2.33"
cranelift = "0.38"
error-chain = "0.12"
http-muncher = "0.3"
lazy_static = "1.3"
libc = "0.2"
may = "0.3"
nix = "0.15"
lalrpop-util="0.17"
log = "0.4"
pretty_env_logger = "0.3"
regex = "1.2"
serde = "1.0"
serde_json = "1.0"
url = "2.1"

[build-dependencies.lalrpop]
version = "0.17"
