[package]
edition = "2018"
name = "cathlamet"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
description = "Distributed systems substrate"
documentation = "https://docs.rs/cathlamet/"
repository= "https://github.com/hmwill/cathlamet"
license = "MIT"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
bitflags = "*"
bytes = "*"
clap = "*"
cranelift = "*"
error-chain = "*"
http-muncher = "*"
lazy_static = "*"
libc = "*"
may = "*"
nix = "*"
lalrpop-util="*"
log = "*"
pretty_env_logger = "*"
regex = "*"
serde = "*"
serde_json = "*"
url = "*"
async-std = "*"

[build-dependencies]
lalrpop = { version = "*", features = ["lexer"] }
